### ISSUE TITLE
Fails test-suite on big-endian s390x

### ISSUE THREAD

**Issue by xnox** [byteverse/byte-order#6]
Hi,

I have access to s390x and byte-order fails tests there

```
touch configure-ghc-stamp
. /usr/share/haskell-devscripts/Dh_Haskell.sh && \
build_recipe
Running debian/hlibrary.setup build --builddir=dist-ghc
Preprocessing library for byte-order-0.1.2.0..
Building library for byte-order-0.1.2.0..
[1 of 4] Compiling System.ByteOrder.Class ( src/System/ByteOrder/Class.hs, dist-ghc/build/System/ByteOrder/Class.o )
[2 of 4] Compiling System.ByteOrder ( src/System/ByteOrder.hs, dist-ghc/build/System/ByteOrder.o )
[3 of 4] Compiling Data.Primitive.ByteArray.LittleEndian ( src/Data/Primitive/ByteArray/LittleEndian.hs, dist-ghc/build/Data/Primitive/ByteArray/LittleEndian.o )
[4 of 4] Compiling Data.Primitive.ByteArray.BigEndian ( src/Data/Primitive/ByteArray/BigEndian.hs, dist-ghc/build/Data/Primitive/ByteArray/BigEndian.o )
[1 of 4] Compiling System.ByteOrder.Class ( src/System/ByteOrder/Class.hs, dist-ghc/build/System/ByteOrder/Class.p_o )
[2 of 4] Compiling System.ByteOrder ( src/System/ByteOrder.hs, dist-ghc/build/System/ByteOrder.p_o )
[3 of 4] Compiling Data.Primitive.ByteArray.LittleEndian ( src/Data/Primitive/ByteArray/LittleEndian.hs, dist-ghc/build/Data/Primitive/ByteArray/LittleEndian.p_o )
[4 of 4] Compiling Data.Primitive.ByteArray.BigEndian ( src/Data/Primitive/ByteArray/BigEndian.hs, dist-ghc/build/Data/Primitive/ByteArray/BigEndian.p_o )
Preprocessing test suite 'unit' for byte-order-0.1.2.0..
Building test suite 'unit' for byte-order-0.1.2.0..
[1 of 1] Compiling Main             ( test/Unit.hs, dist-ghc/build/unit/unit-tmp/Main.o )
Linking dist-ghc/build/unit/unit ...
touch build-ghc-stamp
. /usr/share/haskell-devscripts/Dh_Haskell.sh && \
check_recipe
Running debian/hlibrary.setup test --builddir=dist-ghc --show-details=direct
Running 1 test suites...
Test suite unit: RUNNING...
Start
A
unit: user error (testA: byte 0 was wrong)
Test suite unit: FAIL
Test suite logged to: dist-ghc/test/byte-order-0.1.2.0-unit.log
0 of 1 test suites (0 of 1 test cases) passed.
make: *** [/usr/share/cdbs/1/class/hlibrary.mk:154: check-ghc-stamp] Error 1
```

I am not good at haskell, so I'm not sure how to produce more verbose output.

s390x is also available on travis, not sure if that would be of any help.

Note I first had to fix unaligned package to compile for s390x
http://launchpadlibrarian.net/488162505/haskell-primitive-unaligned_0.1.1.1-1_0.1.1.1-1ubuntu1.diff.gz

**Comment by andrewthad** [comment]
In d427ed09e091905fafefad68fbc32d8804942d8d, I've improved the error message. Could you try building with that? I'm really not sure why this would be failing, but that extra information would help.

**Comment by xnox** [comment]
```
. /usr/share/haskell-devscripts/Dh_Haskell.sh && \
check_recipe
Running debian/hlibrary.setup test --builddir=dist-ghc --show-details=direct
Running 1 test suites...
Test suite unit: RUNNING...
Start
A
unit: user error (testA, byte 0: byte 0 was wrong, expected 103 but got 1)
Test suite unit: FAIL
Test suite logged to: dist-ghc/test/byte-order-0.1.2.0-unit.log
0 of 1 test suites (0 of 1 test cases) passed.
make: *** [/usr/share/cdbs/1/class/hlibrary.mk:154: check-ghc-stamp] Error 1

```

@andrewthad cherrypicked that patch on top of 0.1.2.0 and that's the output i get now.

**Comment by xnox** [comment]
I can't build straight from git, as I do not have wide-word available on s390x yet.

**Comment by xnox** [comment]
It feels like it doesn't realise that it is on big-endian and that "to-bigendian" should be a no-op, whilst "to-littleendian" should do things.

I couldn't find where the code determines / tests what the native layout is.

**Comment by andrewthad** [comment]
The actual byte order comes from [GHC.ByteOrder](https://hackage.haskell.org/package/base-4.12.0.0/docs/src/GHC.ByteOrder.html#ByteOrder). It's possible that GHC sets `WORDS_BIGENDIAN` incorrectly on `s390x`. Try building and running this:

    import qualified GHC.ByteOrder
    main :: IO ()
    main = putStrLn GHC.ByteOrder.targetByteOrder

Also, which one of my libraries are you trying to get to build? People usually only find out about `byte-order` because they're using something else I wrote that depends on it, and if that's the case, there's always a chance that the dependency is not actually necessary.

**Comment by xnox** [comment]
[taffybar](https://github.com/taffybar/taffybar) depends on status-notifier-item.
[status-notifier-item](https://github.com/taffybar/status-notifier-item) in Debian/Ubuntu build-depends on byte-order specifically [here](https://github.com/taffybar/status-notifier-item/blob/master/package.yaml#L23)

And here I am.

If there is a version of haskell-status-notifier-item that doesn't use byte-order, that would be nice.

**Comment by xnox** [comment]
I didn't manage to compile the snippet above because `GHC.ByteOrder.ByteOrder` with `[Char]` didn't match types.

However, I ran ghci and got this

```
# ghci
GHCi, version 8.8.3: https://www.haskell.org/ghc/  :? for help
Prelude> import qualified GHC.ByteOrder
Prelude GHC.ByteOrder> GHC.ByteOrder.targetByteOrder
LittleEndian
```

That can't be good.

**Comment by andrewthad** [comment]
I've [opened an issue on GHC](https://gitlab.haskell.org/ghc/ghc/-/issues/18445) to track this. I suspect that no one has noticed this before because use of the `GHC.ByteOrder` module is uncommon.

**Comment by andrewthad** [comment]
Also, in `status-notifier-item`, the dep on `byte-order` only arrived in [the most recent commit](https://github.com/taffybar/status-notifier-item/commit/c7d8fedeba7a9b65ea265bb8cd79776baec28528). To avoid this dependency, it's possible to fork `status-notifier-item` and call `htonl` through the FFI instead.
